/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentCallbackRouteImport } from './routes/payment-callback'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MomoPaymentRouteImport } from './routes/momo-payment'
import { Route as MarketRouteImport } from './routes/market'
import { Route as InviteUsRouteImport } from './routes/invite-us'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MomoPaymentRoute = MomoPaymentRouteImport.update({
  id: '/momo-payment',
  path: '/momo-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteUsRoute = InviteUsRouteImport.update({
  id: '/invite-us',
  path: '/invite-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/invite-us': typeof InviteUsRoute
  '/market': typeof MarketRoute
  '/momo-payment': typeof MomoPaymentRoute
  '/music': typeof MusicRoute
  '/payment-callback': typeof PaymentCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/invite-us': typeof InviteUsRoute
  '/market': typeof MarketRoute
  '/momo-payment': typeof MomoPaymentRoute
  '/music': typeof MusicRoute
  '/payment-callback': typeof PaymentCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/invite-us': typeof InviteUsRoute
  '/market': typeof MarketRoute
  '/momo-payment': typeof MomoPaymentRoute
  '/music': typeof MusicRoute
  '/payment-callback': typeof PaymentCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-settings'
    | '/cart'
    | '/gallery'
    | '/invite-us'
    | '/market'
    | '/momo-payment'
    | '/music'
    | '/payment-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-settings'
    | '/cart'
    | '/gallery'
    | '/invite-us'
    | '/market'
    | '/momo-payment'
    | '/music'
    | '/payment-callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-settings'
    | '/cart'
    | '/gallery'
    | '/invite-us'
    | '/market'
    | '/momo-payment'
    | '/music'
    | '/payment-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CartRoute: typeof CartRoute
  GalleryRoute: typeof GalleryRoute
  InviteUsRoute: typeof InviteUsRoute
  MarketRoute: typeof MarketRoute
  MomoPaymentRoute: typeof MomoPaymentRoute
  MusicRoute: typeof MusicRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-callback': {
      id: '/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/momo-payment': {
      id: '/momo-payment'
      path: '/momo-payment'
      fullPath: '/momo-payment'
      preLoaderRoute: typeof MomoPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-us': {
      id: '/invite-us'
      path: '/invite-us'
      fullPath: '/invite-us'
      preLoaderRoute: typeof InviteUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CartRoute: CartRoute,
  GalleryRoute: GalleryRoute,
  InviteUsRoute: InviteUsRoute,
  MarketRoute: MarketRoute,
  MomoPaymentRoute: MomoPaymentRoute,
  MusicRoute: MusicRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
